dist: trusty
language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5.4
    - ninja-build

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export CC="gcc-5.4"; export CXX="g++-5.4"; fi

script:
  - mkdir build
  - cd build
  - cmake -G Ninja -DENABLE_ADE_TESTING=ON -DBUILD_ADE_TUTORIAL=ON .. && ninja && ctest
